

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog_app_development
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://postgres:password@db:5432/blog_app_development
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis
    command: bash -c "bundle exec rails db:migrate &&  bundle exec rails s -b 0.0.0.0 -p 3000"
  sidekiq:
    build:
      context: .
    depends_on:
      - db
      - redis
    volumes:
      - .:/rails
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://postgres:password@db:5432/blog_app_development
      REDIS_URL: redis://redis:6379/0
    command: bundle exec sidekiq

volumes:
  pgdata:
